import { Inter } from 'next/font/google'
import './globals.css'

import { Providers } from "./providers";

import { UserProvider } from './userContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html  className="dark text-foreground bg-background" lang="en">
       <body className={inter.className} >
        <UserProvider>
          <Providers>
            <main >
              {children}

            </main>
          </Providers>
        </UserProvider>
      </body>
    </html>
  )
}
